# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - azure-pipelines
#- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: terraform version
  displayName: 'Check terraform'

- task: AzureCLI@2
  displayName: Azure CLI@2 checking
  inputs:
    azureSubscription: 'Azure service connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show


# - task: TerraformInstaller
#   displayName: install terraform
#   inputs:
#     terraformVersion: 1.1.7

# - task: TerraformCLI@0
#   displayName: 'check terraform version'
#   inputs:
#     command: version

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
